on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
name: Test
jobs:
    test:
        strategy:
            matrix:
                go-version: [1.23.x, 1.24.x, 1.25.x]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-go@v4
              with:
                  go-version: "${{ matrix.go-version }}"
            - uses: actions/checkout@v3
            - name: Test
              run: go test -v ./...
